package com.ecommerce.analytics.event;

public enum EventType {

    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,

    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,

    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,

    CART_CREATED,
    CART_UPDATED,
    CART_DELETED,

    CART_ITEM_ADDED,
    CART_ITEM_UPDATED,
    CART_ITEM_REMOVED,

    ORDER_CREATED,
    ORDER_STATUS_CHANGED,
    ORDER_DELETED,

    PAYMENT_CREATED,
    PAYMENT_DELETED,

    REVIEW_CREATED,
    REVIEW_UPDATED,
    REVIEW_DELETED
}